title: Jake Hanson # your name (or website title) here
logo: "/images/circle_headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Theoretical physicist with a diverse skill set. Peer-reviewed publications in the fields of cognitive neuroscience, entomology, and exoplanetary science.
  <br><br>
  PhD Astrophysics, with a focus on data-driven models and information theory.
  <br><br>
  BS Physics, BS Astronomy, BS Applied Mathematics
  <br><br>
  <a href="https://scholar.google.com/citations?user=jEuPs24AAAAJ&hl=en&oi=ao">View my Google Scholar</a> 
  <br>
  <a href="https://github.com/jakehanson">View my GitHub Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/jake-hanson-048243159/">View my LinkedIn Profile</a>


  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
